routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/','PagesController@root')->name('root');
Auth::routes();
Route::redirect('/','/products')->name('root');
Route::get('products','ProductsController@index')->name('products.index');


Route::group(['middleware'=> ['auth']],function(){
    // 验证邮箱页面 发送邮件
    Route::get('/email_verify_notice','PagesController@emailVerifyNotice')->name('email_verify_notice');
    // 点击按钮 发送邮件
    Route::get('/email_verification/send','EmailVerificationController@send')->name('email_verification.send');
    // 邮件中的验证链接
    Route::get('/email_verification/verify','EmailVerificationController@verify')->name('email_verification.verify');

    // 加入了验证邮箱的中间件
    Route::group(['middleware' =>['email_verified']],function(){
        // 收货地址列表页面
        Route::get('/user_address','UserAddressesController@index')->name('user_addresses.index');
        // 新增收货地址页面
        Route::get('/user_address/create','UserAddressesController@create')->name('user_addresses.create');
        // 收货地址逻辑
        Route::post('/user_address','UserAddressesController@store')->name('user_addresses.store');
        // 编辑收货地址
        Route::get('/user_address/{user_address}','UserAddressesController@edit')->name('user_addresses.edit');
        // 编辑收货地址逻辑
        Route::patch('/user_address/{user_address}','UserAddressesController@update')->name('user_addresses.update');
        // 删除收货地址
        Route::delete('/user_addresses/{user_address}','UserAddressesController@destroy')->name('user_addresses.destroy');
        // 收藏商品
        Route::post('products/{product}/favorite','ProductsController@favor')->name('products.favor');
        // 取消收藏商品
        Route::delete('products/{product}/favorite','ProductsController@disfavor')->name('products.disfavor');
        // 我的收藏
        Route::get('products/favorites','ProductsController@favorites')->name('products.favorites');
        // 加入购物车
        Route::post('cart','CartController@add')->name('cart.add');
        // 我的购物车列表
        Route::get('cart','CartController@index')->name('cart.index');
        // 删除购物车选项
        Route::delete('cart/{sku}','CartController@remove')->name('cart.remove');

    });

});
// 商品详情
Route::get('products/{product}','ProductsController@show')->name('products.show');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Product extends Model{
    protected $fillable = [
        'title','description','image','on_sale','rating','sold_count','review_count','price'
    ];

    // 与商品sku 关联
    public function skus(){
        return $this->hasMany(ProductSku::class);
    }

    public function getImageUrlAttribute(){
        // 如果image 字段本身就已经是完整的url 就直接返回
        if(Str::startsWith($this->attributes['image'],['http://','https://'])){
            return $this->attributes['image'];
        }
        return \Storage::disk('public')->url($this->attributes['image']);
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;
use App\Exceptions\InvalidRequestException;

class ProductsController extends Controller{
    public function index(Request $request){
        // 创建一个查询构造器
        $builder = Product::query()->where('on_sale',1);
        // 判断是否有提交 search 参数，如果有就赋值给 $search 变量
        // search 参数用来模糊搜索商品
        if($search = $request->input('search','')){
            $like = '%'.$search.'%';
            // 模糊搜索商品标题、商品详情、sku 标题、sku 描述
            $builder->where(function($query) use($like){
                $query->where('title','like',$like)
                        ->orWhere('description','like',$like)
                        ->orWhereHas('skus',function($query) use($like){
                            $query->where('title','like',$like)
                                    ->orWhere('description','like',$like);
                        });
            });
        }

        // 是否有提交 order 参数，如果有就赋值给 $order 变量
        // order 参数用来控制商品的排序规则
        if($order = $request->input('order','')){
            // 是否是以_asc 或者 _desc 结尾
            if(preg_match('/^(.+)_(asc|desc)$/',$order,$m)){
                if(in_array($m[1],['price','sold_count','rating'])){
                    // 根据传入的排序值来构造排序函数
                    $builder->orderBy($m[1],$m[2]);
                }
            }
        }
        $products = $builder->paginate(16);
        $filters = [
            'search' => $search,
            'order' => $order
        ];
        return view('products.index',compact('products','filters'));
    }

    public function show(Product $product,Request $request){
        // 判断商品是否已经上架，如果没有上架则抛出异常.
        if(!$product->on_sale){
            throw new InvalidRequestException('商品未上架');
        }
        $favored = false;
        // 用户未登录是返回的是null,已登录是返回的是对应的用户对象
        if($user = $request->user()){
            // 从当前用户已收藏的商品中搜索id 为当前商品id 的商品
            // boolval() 函数用于把值转为布尔值
            $favored = boolval($user->favoriteProducts()->find($product->id));
        }

        return view('products.show',compact('product','favored'));
    }

    // 收藏商品
    public function favor(Product $product,Request $request){
        $user = $request->user();
        if($user->favoriteProducts()->find($product->id)){
            return [];
        }

        $user->favoriteProducts()->attach($product);
        return [];
    }

    // 取消收藏商品
    public function disfavor(Product $product,Request $request){
        $user = $request->user();
        $user->favoriteProducts()->detach($product);
        return [];
    }

    // 我的收藏商品列表
    public function favorites(Request $request){
        $products = $request->user()->favoriteProducts()->paginate(16);
        return view('products.favorites',compact('products'));
    }
}

resources/views/products/favorites.blade.php
@extends('layouts.app')

@section('title','我的收藏')

@section('content')
    <div class="row">
        <div class="col-lg-10 col-lg-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">我的收藏</div>
                <div class="panel-body">
                    <div class="row products-list">
                        @foreach($products as $product)
                            <div class="col-xs-3 product-item">
                                <div class="product-content">
                                    <div class="top">
                                        <div class="img">
                                            <a href="{{ route('products.show',['product' => $product->id]) }}">
                                                <img src="{{ $product->image_url }}" alt="">
                                            </a>
                                        </div>
                                        <div class="price">
                                            <b>￥</b>{{ $product->price }}
                                        </div>
                                        <a href="{{ route('products.show',['product' => $product->id]) }}">
                                            {{ $product->title }}
                                        </a>
                                    </div>
                                    <div class="bottom">
                                        <div class="sold_count">
                                            销量<span>{{ $product->sold_count }}笔</span>
                                        </div>
                                        <div class="review_count">
                                            评价<span>{{ $product->review_count }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                    <div class="pull-right">{{ $products->render() }}</div>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/products/index.blade.php
@extends('layouts.app')
@section('title','商品列表')

@section('content')
<div class="row">
    <div class="col-lg-10 col-lg-offset-1">
        <div class="panel panel-default">
            <div class="panel-body">
                {{-- 筛选 排序 --}}
                <div class="row">
                    <form action="{{ route('products.index') }}" class="form-inline search-form">
                        <input type="text" class="form-control input-sm" name="search" placeholder="搜索">
                        <button class="btn btn-primary btn-sm">搜索</button>
                        <select name="order" class="form-control input-sm pull-right">
                            <option value="">排序方式</option>
                            <option value="price_asc">价格从低到高</option>
                            <option value="price_desc">价格从高到低</option>
                            <option value="sold_count_desc">销量从高到低</option>
                            <option value="sold_count_asc">销量从低到高</option>
                            <option value="rating_desc">评价从高到低</option>
                            <option value="rating_asc">评价从低到高</option>

                        </select>
                    </form>
                </div>
                <div class="row products-list">
                    @foreach($products as $product)
                        <div class="col-xs-3 product-item">
                            <div class="product-content">
                                <div class="top">
                                    <div class="img">
                                        <a href="{{ route('products.show',['product' => $product->id]) }}">
                                            <img src="{{ $product->image_url }}" alt="">
                                        </a>
                                    </div>
                                    <div class="price"><b>￥</b>{{ $product->price }}</div>
                                    <div class="title">
                                        <a href="{{ route('products.show',['product' => $product->id]) }}">
                                            {{ $product->title }}
                                        </a>
                                    </div>
                                </div>
                                <div class="bottom">
                                    <div class="sold_count">销量<span>{{ $product->sold_count }}笔</span></div>
                                    <div class="review_count">评价<span>{{ $product->review_count }}</span></div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
                {{-- 分页 --}}
                <div class="pull-right">
                    {{-- appends() 方法接受一个 Key-Value 形式的数组作为参数，在生成分页链接的时候会把这个数组格式化成查询参数。 --}}
                    {{ $products->appends($filters)->render() }}
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@section('scriptsAfterJs')
<script type="text/javascript">
    var filters = {!! json_encode($filters) !!}
    $(document).ready(function(){
        $('.search-form input[name=search]').val(filters.search);
        $('.search-form select[name=order]').val(filters.order);

        $('.search-form select[name=order]').change(function(){
            $('.search-form').submit();
        });
    });
</script>
@stop

resources/views/products/show.blade.php
@extends('layouts.app')
@section('title', $product->title)

@section('content')
<div class="row">
<div class="col-lg-10 col-lg-offset-1">
<div class="panel panel-default">
  <div class="panel-body product-info">
    <div class="row">
      <div class="col-sm-5">
        <img class="cover" src="{{ $product->image_url }}" alt="">
      </div>
      <div class="col-sm-7">
        <div class="title">{{ $product->title }}</div>
        <div class="price"><label>价格</label><em>￥</em><span>{{ $product->price }}</span></div>
        <div class="sales_and_reviews">
          <div class="sold_count">累计销量 <span class="count">{{ $product->sold_count }}</span></div>
          <div class="review_count">累计评价 <span class="count">{{ $product->review_count }}</span></div>
          <div class="rating" title="评分 {{ $product->rating }}">评分 <span class="count">{{ str_repeat('★', floor($product->rating)) }}{{ str_repeat('☆', 5 - floor($product->rating)) }}</span></div>
        </div>
        <div class="skus">
          <label>选择</label>
          <div class="btn-group" data-toggle="buttons">
            @foreach($product->skus as $sku)
              <label class="btn btn-default sku-btn" data-price="{{ $sku->price }}" data-stock="{{ $sku->stock }}" data-toggle="tooltip" title="{{ $sku->description }}" data-placement="bottom">
                <input type="radio" name="skus" autocomplete="off" value="{{ $sku->id }}" />{{ $sku->title }}
              </label>
            @endforeach
          </div>
        </div>
        <div class="cart_amount"><label>数量</label><input type="text" class="form-control input-sm" value="1"><span>件</span><span class="stock"></span></div>
        <div class="buttons">
          @if($favored)
            <button class="btn btn-danger btn-disfavor">取消收藏</button>
          @else
            <button class="btn btn-success btn-favor">❤ 收藏</button>
          @endif

          <button class="btn btn-primary btn-add-to-cart">加入购物车</button>
        </div>
      </div>
    </div>
    <div class="product-detail">
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#product-detail-tab" aria-controls="product-detail-tab" role="tab" data-toggle="tab">商品详情</a></li>
        <li role="presentation"><a href="#product-reviews-tab" aria-controls="product-reviews-tab" role="tab" data-toggle="tab">用户评价</a></li>
      </ul>
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="product-detail-tab">
          {!! $product->description !!}
        </div>
        <div role="tabpanel" class="tab-pane" id="product-reviews-tab">
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
@endsection

@section('scriptsAfterJs')
<script type="text/javascript">
    $(document).ready(function(){
        $('[data-toggle="tooltip"]').tooltip({trigger:'hover'});
        $('.sku-btn').click(function(){
            $('.product-info .price span').text($(this).data('price'));
            $('.product-info .stock').text('库存:' + $(this).data('stock')+'件');
        });

        // 监听收藏按钮的点击事件
        $('.btn-favor').click(function(){
            // 发起一个post ajax 请求，请求url 通过后端的route() 函数生成。
            axios.post("{{ route('products.favor',['product' => $product->id]) }}")
                    .then(function(){
                        // 请求成功会执行这个回调
                        swal('操作成功','','success');
                    },function(error){
                        // 请求失败会执行这个回调
                        // 如果返回码是 401 代表没登录
                        if(error.response && error.response.status === 401){
                            swal('请先登录','','error');
                        }else{
                            // 其他情况应该是系统挂了
                            swal('系统错误','','error');
                        }
                    });
        });

        // 监听取消收藏按钮的点击事件
        $('.btn-disfavor').click(function(){
            axios.delete("{{ route('products.disfavor',['product' => $product->id]) }}")
                    .then(function(){
                        swal('操作成功','','success')
                            .then(function(){
                                location.reload();
                            });
                    });
        });

        // 加入购物车按钮点击事件
        $('.btn-add-to-cart').click(function(){
            // 请求加入购物车接口
            axios.post("{{ route('cart.add') }}",{
                sku_id:$('label.active input[name=skus]').val(),
                amount:$('.cart_amount input').val()
            })
            .then(function(){
                // 请求成功执行此回调
                swal('加入购物车成功','','success')
                .then(function(){
                    location.href='{{ route('cart.index') }}';
                });
            },function(error){
                if(error.response.status === 401){
                    // http 状态码为401 代表用户未登录
                    swal('请先登录','','error');
                }else if(error.response.status === 422){
                    // http 状态码为422 代表用户输入校验失败
                    var html = '<div>';
                    _.each(error.response.data.errors,function(errors){
                        _.each(errors,function(error){
                            html += error + '<br />';
                        })
                    });
                    html += '</div>';
                    swal({content:$(html)[0],icon:'error'})
                }else{
                    // 其他情况应该是系统挂了
                    swal('系统错误','','error');
                }
            })
        });
    });
</script>
@stop